server:
  port: 8081
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    ip-address: 127.0.0.1
    prefer-ip-address: true
    status-page-url: http://${eureka.instance.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
spring:
  application:
    name: admin-server