server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
      globalcors:
        '[/**]':
          allowedOrigins: "*"
          allowedMethods:
            - GET
            - PUT
            - POST
            - DELETE
            - OPTIONS
      routes:
        - id: jd
          uri: http://www.jd.com
          predicates:
            - Method=GET
  redis:
    host: localhost
    port: 6379
    url: http://127.0.0.1:6379
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    prefer-ip-address: true # 是否优先使用ip地址代替hostname作为实例的hostName字段值
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
ribbon:
  eager-load:
    enabled: true

order:
  ribbon:
    listOfServers: http://order:8081,http://order:8082,http://order:8083
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    ServerListRefreshInterval: 2000
    retryableStatusCodes: 500
    ConnectTimeout: 500
    ReadTimeout: 20000
    OkToRetryOnAllOperations: true
    MaxAutoRetriesNextServer: 2
    MaxAutoRetries: 0

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 # 超时时间