server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:10086/eureka
#  instance:
#    prefer-ip-address: true # 是否优先使用ip地址代替hostname作为实例的hostName字段值
#    ip-address: 127.0.0.1
#    instance-id: ${spring.application.name}:${server.port}
zuul:
  routes:
    item-service: /item/**
  prefix: /api