server:
  port: 8081
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/book
  thymeleaf:
    cache: false
  application:
    name: item-service
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
    nacos:
      config:
        server-addr: 127.0.0.1:8848
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    port: 6379
    database: 1
    timeout: 5000
    jedis:
      pool:
        max-active: 300
        max-wait: 2000
    host: 127.0.0.1
  rabbitmq:
    host: 127.0.0.1
    username: leyou
    password: leyou
    virtual-host: /leyou
    template:
      exchange: purchase_exchange
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:10086/eureka
#  instance:
#    prefer-ip-address: true
#    ip-address: 127.0.0.1
#    instance-id: ${spring.application.name}:${server.port}